(ql:quickload :cl-conllu)
(ql:quickload :alexandria)
(ql:quickload :cl-fad)

(in-package :cl-conllu)

;; note: doesn't add a new feature if there is one with the same name
;; we should enhance it when needed:
;; 1. If adding Foo=Bar and Foo=Bar is already a feature, ignore
;; 2. If adding Foo=Bar and Foo=Baz is already a feature, add Foo=Bar,Baz
(defun append-feature (key value token)
  (let* ((features-str (slot-value token 'misc))
         (features (if (string= "_" features-str) nil
                       (split-sequence #\| features-str))))
    (format nil "~{~a~^|~}" (sort (append features `(,(if (and key value) 
                                                          (format nil "~a=~a" key value)
                                                          (format nil "~a" value)))) #'string<))))

(defun search-feature (key-value features)
  (find key-value (split-sequence #\| features) 
        :test #'string=))

(defun t? (token &key lemma form misc)
  (and 
   (if (and (atom misc) misc)
       (search-feature misc (slot-value token 'misc))
       t)
   (if (and (atom form) form)
        (string-equal (slot-value token 'form) form)
       t)
   (if (and (atom lemma) lemma)
        (string-equal (slot-value token 'lemma) lemma)
       t)))

(defparameter *fixed-lemmas* '(("Conhecido" "conhecer" "conhecido")
                               ("Indignados" "indignar" "indignado")
                               ("Interessado" "interessar" "interessado")
                               ("Irritado" "irritar" "irritado")
                               ("Ligada" "ligar" "ligado")
                               ("Preocupado" "preocupar" "preocupado")
                               ("abananadas" "abananar" "abananado")
                               ("aberta" "abrir" "aberto")
                               ("abertas" "abrir" "aberto")
                               ("aberto" "abrir" "aberto")
                               ("abertos" "abrir" "aberto")
                               ("abrangidas" "abranger" "abrangido")
                               ("acabado" "acabar" "acabado")
                               ("acalorados" "acalorar" "acalorado")
                               ("aceita" "aceitar" "aceito")
                               ("acertado" "acertar" "acertado")
                               ("acompanhados" "acompanhar" "acompanhado")
                               ("acostumado" "acostumar" "acostumado")
                               ("acostumados" "acostumar" "acostumado")
                               ("adaptados" "adaptar" "adaptado")
                               ("adequada" "adequar" "adequado")
                               ("adequadas" "adequar" "adequado")
                               ("adequado" "adequar" "adequado")
                               ("adiada" "adiar" "adiado")
                               ("adormecido" "adormecer" "adormecido")
                               ("afastada" "afastar" "afastado")
                               ("afetada" "afetar" "afetado")
                               ("aflita" "afligir" "aflito")
                               ("aguçado" "aguçar" "aguçado")
                               ("alargado" "alargar" "alargado")
                               ("amadurecida" "amadurecer" "amadurecido")
                               ("amarrotados" "amarrotar" "amarrotado")
                               ("ameaçada" "ameaçar" "ameaçado")
                               ("angustiada" "angustiar" "angustiado")
                               ("angustiado" "angustiar" "angustiado")
                               ("apaixonada" "apaixonar" "apaixonado")
                               ("apaixonado" "apaixonar" "apaixonado")
                               ("aposentado" "aposentar" "aposentado")
                               ("aposentados" "aposentar" "aposentado")
                               ("apressada" "apressar" "apressado")
                               ("apretechada" "apretechar" "apretechado")
                               ("aprofundada" "aprofundar" "aprofundado")
                               ("aproveitada" "aproveitar" "aproveitado")
                               ("apurado" "apurar" "apurado")
                               ("arborizado" "arborizar" "arborizado")
                               ("arredados" "arredar" "arredado")
                               ("arrependido" "arrepender" "arrependido")
                               ("assentes" "assentar" "assente")
                               ("assinado" "assinar" "assinado")
                               ("assinados" "assinar" "assinado")
                               ("associada" "associar" "associado")
                               ("assustados" "assustar" "assustado")
                               ("atingidas" "atingir" "atingido")
                               ("atingido" "atingir" "atingido")
                               ("atolados" "atolar" "atolado")
                               ("atordoada" "atordoar" "atordoado")
                               ("atrasadas" "atrasar" "atrasado")
                               ("atrasados" "atrasar" "atrasado")
                               ("avaliada" "avaliar" "avaliado")
                               ("avançado" "avançar" "avançado")
                               ("badaladas" "badalar" "badalado")
                               ("baralhados" "baralhar" "baralhado")
                               ("baseada" "basear" "baseado")
                               ("bem-sucedidas" "bem-suceder" "bem-sucedido")
                               ("cansadas" "cansar" "cansado")
                               ("cansado" "cansar" "cansado")
                               ("casada" "casar" "casado")
                               ("casado" "casar" "casado")
                               ("caído" "cair" "caído")
                               ("centradas" "centrar" "centrado")
                               ("cercado" "cercar" "cercado")
                               ("cercados" "cercar" "cercado")
                               ("cerrado" "cerrar" "cerrado")
                               ("civilizados" "civilizar" "civilizado")
                               ("cobertos" "cobrir" "coberto")
                               ("colocado" "colocar" "colocado")
                               ("colocados" "colocar" "colocado")
                               ("combinados" "combinar" "combinado")
                               ("comedido" "comedir" "comedido")
                               ("complicada" "complicar" "complicado")
                               ("complicadas" "complicar" "complicado")
                               ("complicado" "complicar" "complicado")
                               ("comprometida" "comprometer" "comprometido")
                               ("concentrados" "concentrar" "concentrado")
                               ("concluída" "concluir" "concluído")
                               ("concorrida" "concorrer" "concorrido")
                               ("concorrido" "concorrer" "concorrido")
                               ("condenados" "condenar" "condenado")
                               ("condensado" "condensar" "condensado")
                               ("condicionada" "condicionar" "condicionado")
                               ("conduzida" "conduzir" "conduzido")
                               ("conectada" "conectar" "conectado")
                               ("confirmada" "confirmar" "confirmado")
                               ("conformada" "conformar" "conformado")
                               ("conformados" "conformar" "conformado")
                               ("conhecida" "conhecer" "conhecido")
                               ("conhecidas" "conhecer" "conhecido")
                               ("conhecido" "conhecer" "conhecido")
                               ("conhecidos" "conhecer" "conhecido")
                               ("consagrada" "consagrar" "consagrado")
                               ("consagrado" "consagrar" "consagrado")
                               ("constituído" "constituir" "constituído")
                               ("convencido" "convencer" "convencido")
                               ("cotada" "cotar" "cotado")
                               ("cotado" "cotar" "cotado")
                               ("criadas" "criar" "criado")
                               ("cuidada" "cuidar" "cuidado")
                               ("decepcionado" "decepcionar" "decepcionado")
                               ("decidido" "decidir" "decidido")
                               ("decididos" "decidir" "decidido")
                               ("decorado" "decorar" "decorado")
                               ("decorrida" "decorrer" "decorrido")
                               ("decorridos" "decorrer" "decorrido")
                               ("definidas" "definir" "definido")
                               ("definido" "definir" "definido")
                               ("definidos" "definir" "definido")
                               ("degradada" "degradar" "degradado")
                               ("deitado" "deitar" "deitado")
                               ("deprimida" "deprimir" "deprimido")
                               ("desempregado" "desempregar" "desempregado")
                               ("desencantados" "desencantar" "desencantado")
                               ("desenvolvido" "desenvolver" "desenvolvido")
                               ("desfavorecidos" "desfavorecer" "desfavorecido")
                               ("desobrigado" "desobrigar" "desobrigado")
                               ("destacados" "destacar" "destacado")
                               ("destinado" "destinar" "destinado")
                               ("destinados" "destinar" "destinado")
                               ("determinada" "determinar" "determinado")
                               ("difundidos" "difundir" "difundido")
                               ("dirigido" "dirigir" "dirigido")
                               ("discutido" "discutir" "discutido")
                               ("disposta" "dispor" "disposto")
                               ("dispostas" "dispor" "disposto")
                               ("disposto" "dispor" "disposto")
                               ("dispostos" "dispor" "disposto")
                               ("distraídos" "distrair" "distraído")
                               ("distribuído" "distribuir" "distribuído")
                               ("divertida" "divertir" "divertido")
                               ("divertidas" "divertir" "divertido")
                               ("divertido" "divertir" "divertido")
                               ("divertidos" "divertir" "divertido")
                               ("dotada" "dotar" "dotado")
                               ("elevada" "elevar" "elevado")
                               ("elevado" "elevar" "elevado")
                               ("empenhada" "empenhar" "empenhado")
                               ("empenhadas" "empenhar" "empenhado")
                               ("empenhado" "empenhar" "empenhado")
                               ("encarregado" "encarregar" "encarregado")
                               ("encerrada" "encerrar" "encerrado")
                               ("encorpados" "encorpar" "encorpado")
                               ("engajado" "engajar" "engajado")
                               ("engraçadas" "engraçar" "engraçado")
                               ("enlameado" "enlamear" "enlameado")
                               ("envelhecido" "envelhecer" "envelhecido")
                               ("envolvida" "envolver" "envolvido")
                               ("envolvido" "envolver" "envolvido")
                               ("enxovalhados" "enxovalhar" "enxovalhado")
                               ("equilibrada" "equilibrar" "equilibrado")
                               ("equilibrado" "equilibrar" "equilibrado")
                               ("equipados" "equipar" "equipado")
                               ("errado" "errar" "errado")
                               ("escalado" "escalar" "escalado")
                               ("escalonada" "escalonar" "escalonado")
                               ("escolhidas" "escolher" "escolhido")
                               ("escondidas" "esconder" "escondido")
                               ("esgotadas" "esgotar" "esgotado")
                               ("especializada" "especializar" "especializado")
                               ("esperançados" "esperançar" "esperançado")
                               ("esquecido" "esquecer" "esquecido")
                               ("esquecidos" "esquecer" "esquecido")
                               ("estabelecidas" "estabelecer" "estabelecido")
                               ("estacionado" "estacionar" "estacionado")
                               ("estimado" "estimar" "estimado")
                               ("exaustos" "exaurir" "exausto")
                               ("excluída" "excluir" "excluído")
                               ("excluído" "excluir" "excluído")
                               ("explicada" "explicar" "explicado")
                               ("exposto" "expor" "exposto")
                               ("falada" "falar" "falado")
                               ("fascinadas" "fascinar" "fascinado")
                               ("feita" "fazer" "feito")
                               ("feito" "fazer" "feito")
                               ("feitos" "fazer" "feito")
                               ("feridas" "ferir" "ferido")
                               ("ferido" "ferir" "ferido")
                               ("feridos" "ferir" "ferido")
                               ("firmada" "firmar" "firmado")
                               ("fixa" "fixar" "fixo")
                               ("fixado" "fixar" "fixado")
                               ("fixo" "fixar" "fixo")
                               ("fixos" "fixar" "fixo")
                               ("foragidos" "foragir" "foragido")
                               ("formado" "formar" "formado")
                               ("furado" "furar" "furado")
                               ("garantida" "garantir" "garantido")
                               ("garantido" "garantir" "garantido")
                               ("garantidos" "garantir" "garantido")
                               ("generalizada" "generalizar" "generalizado")
                               ("generalizadas" "generalizar" "generalizado")
                               ("geridos" "gerir" "gerido")
                               ("grudados" "grudar" "grudado")
                               ("habilitado" "habilitar" "habilitado")
                               ("hasteada" "hastear" "hasteado")
                               ("honrada" "honrar" "honrado")
                               ("hospedado" "hospedar" "hospedado")
                               ("humanizado" "humanizar" "humanizado")
                               ("imortalizada" "imortalizar" "imortalizado")
                               ("impedidos" "impedir" "impedido")
                               ("incluídos" "incluir" "incluído")
                               ("indicado" "indicar" "indicado")
                               ("industrializados" "industrializar" "industrializado")
                               ("instalado" "instalar" "instalado")
                               ("instituída" "instituir" "instituído")
                               ("integrada" "integrar" "integrado")
                               ("interessada" "interessar" "interessado")
                               ("interessadas" "interessar" "interessado")
                               ("interessado" "interessar" "interessado")
                               ("interessados" "interessar" "interessado")
                               ("internada" "internar" "internado")
                               ("internado" "internar" "internado")
                               ("intoxicado" "intoxicar" "intoxicado")
                               ("irritada" "irritar" "irritado")
                               ("irritado" "irritar" "irritado")
                               ("juntos" "juntar" "junto")
                               ("ladeado" "ladear" "ladeado")
                               ("ligadas" "ligar" "ligado")
                               ("ligado" "ligar" "ligado")
                               ("localizadas" "localizar" "localizado")
                               ("maltratados" "maltratar" "maltratado")
                               ("marcado" "marcar" "marcado")
                               ("mortas" "morrer" "morto")
                               ("morto" "morrer" "morto")
                               ("motivado" "motivar" "motivado")
                               ("motivados" "motivar" "motivado")
                               ("obrigados" "obrigar" "obrigado")
                               ("obstinados" "obstinar" "obstinado")
                               ("oposta" "opor" "oposto")
                               ("opostas" "opor" "oposto")
                               ("oposto" "opor" "oposto")
                               ("opostos" "opor" "oposto")
                               ("orçado" "orçar" "orçado")
                               ("ousadas" "ousar" "ousado")
                               ("parado" "parar" "parado")
                               ("parecida" "parecer" "parecido")
                               ("parecidos" "parecer" "parecido")
                               ("partilhada" "partilhar" "partilhado")
                               ("passada" "passar" "passado")
                               ("passadas" "passar" "passado")
                               ("passado" "passar" "passado")
                               ("passados" "passar" "passado")
                               ("perdido" "perder" "perdido")
                               ("perturbado" "perturbar" "perturbado")
                               ("ponderada" "ponderar" "ponderado")
                               ("pranteada" "prantear" "pranteado")
                               ("preocupada" "preocupar" "preocupado")
                               ("preocupadas" "preocupar" "preocupado")
                               ("preocupado" "preocupar" "preocupado")
                               ("preocupados" "preocupar" "preocupado")
                               ("preparada" "preparar" "preparado")
                               ("presas" "prender" "preso")
                               ("preso" "prender" "preso")
                               ("prevista" "prever" "previsto")
                               ("previstas" "prever" "previsto")
                               ("previsto" "prever" "previsto")
                               ("prezada" "prezar" "prezado")
                               ("procurado" "procurar" "procurado")
                               ("procurados" "procurar" "procurado")
                               ("proibida" "proibir" "proibido")
                               ("protegida" "proteger" "protegido")
                               ("protegidas" "proteger" "protegido")
                               ("provado" "provar" "provado")
                               ("provido" "prover" "provido")
                               ("publicitado" "publicitar" "publicitado")
                               ("pulverizada" "pulverizar" "pulverizado")
                               ("querido" "querer" "querido")
                               ("recebida" "receber" "recebido")
                               ("recolhido" "recolher" "recolhido")
                               ("recomendados" "recomendar" "recomendado")
                               ("recuados" "recuar" "recuado")
                               ("reduzida" "reduzir" "reduzido")
                               ("reduzidos" "reduzir" "reduzido")
                               ("registado" "registar" "registado")
                               ("regulamentada" "regulamentar" "regulamentado")
                               ("reiterado" "reiterar" "reiterado")
                               ("relacionada" "relacionar" "relacionado")
                               ("relacionado" "relacionar" "relacionado")
                               ("relacionados" "relacionar" "relacionado")
                               ("rendida" "render" "rendido")
                               ("representada" "representar" "representado")
                               ("representados" "representar" "representado")
                               ("resolvida" "resolver" "resolvido")
                               ("respeitados" "respeitar" "respeitado")
                               ("reunida" "reunir" "reunido")
                               ("reunido" "reunir" "reunido")
                               ("reunidos" "reunir" "reunido")
                               ("sagrado" "sagrar" "sagrado")
                               ("satisfeito" "satisfazer" "satisfeito")
                               ("sediadas" "sediar" "sediado")
                               ("seguras" "segurar" "seguro")
                               ("sensibilizado" "sensibilizar" "sensibilizado")
                               ("separadas" "separar" "separado")
                               ("separados" "separar" "separado")
                               ("situado" "situar" "situado")
                               ("sofisticada" "sofisticar" "sofisticado")
                               ("submersa" "submergir" "submerso")
                               ("submetidos" "submeter" "submetido")
                               ("subordinada" "subordinar" "subordinado")
                               ("sucedidas" "suceder" "sucedido")
                               ("sucedido" "suceder" "sucedido")
                               ("sujeita" "sujeitar" "sujeito")
                               ("sujeito" "sujeitar" "sujeito")
                               ("suposta" "supor" "suposto")
                               ("supostas" "supor" "suposto")
                               ("suposto" "supor" "suposto")
                               ("surpreendido" "surpreender" "surpreendido")
                               ("suspensas" "suspender" "suspenso")
                               ("tentado" "tentar" "tentado")
                               ("terciarizado" "terciarizar" "terciarizado")
                               ("terminados" "terminar" "terminado")
                               ("tolhido" "tolher" "tolhido")
                               ("trabalhadas" "trabalhar" "trabalhado")
                               ("traduzida" "traduzir" "traduzido")
                               ("traduzido" "traduzir" "traduzido")
                               ("trancados" "trancar" "trancado")
                               ("ultrapassados" "ultrapassar" "ultrapassado")
                               ("valorizado" "valorizar" "valorizado")
                               ("variados" "variar" "variado")
                               ("vendidos" "vender" "vendido")
                               ("vetados" "vetar" "vetado")
                               ("viajado" "viajar" "viajado")
                               ("visados" "visar" "visado")
                               ("vista" "ver" "visto")
                               ("vista" "vestir" "visto")
                               ("vistas" "ver" "visto")
                               ("visto" "ver" "visto")
                               ("vocacionado" "vocacionar" "vocacionado")
                               ("voltada" "voltar" "voltado")
                               ("voltados" "voltar" "voltado")
                               ("votado" "votar" "votado")
                               ("zangados" "zangar" "zangado")))

(defun fix-lemma (form old-lemma new-lemma tokens)
  (dolist (tk tokens)
    (when (and (t? tk :misc "ChangedBy=Issue91")
               (t? tk :form form)
               (t? tk :lemma old-lemma))
      (setf (slot-value tk 'lemma) new-lemma)
      (setf (slot-value tk 'misc) (append-feature "ChangedBy" "Issue141" tk)))))

(defun fix-corpus (sentences)
  (dolist (fix *fixed-lemmas*)
    (mapc (lambda (s) 
            (fix-lemma (first fix) (second fix) (third fix) (sentence-tokens s))) sentences))
  sentences)

;; to replicate
;; (write-conllu (fix-corpus (read-conllu "bosque.udep.conll")) "bosque.fixed")
(defun run ()
  (dolist (f (cl-fad:list-directory #p "documents/"))
    (write-conllu (fix-corpus (read-conllu f)) f)))
;; and then concatenate all documents/* into bosque.udep.conll (via
;; join-documents.sh)
